name: Deploy
on:
    push:
        branches: ["main"]
    workflow_dispatch:

concurrency:
    group: "deploy"
    cancel-in-progress: true

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v3
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Node Setup
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Move files
              uses: appleboy/scp-action@v0.1.7
              with:
                  host: violet-server-vm
                  port: 22
                  source: dist/*
                  target: /var/www/portfolio
                  rm: true
