name: Build and deploy static site
on:
    push:
        branches: ["main"]
    workflow_dispatch:

concurrency:
    group: "build-and-deploy"
    cancel-in-progress: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Tailscale
              uses: tailscale/github-action@v3
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Node Setup
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: "npm"
            - name: Install dependencies
              run: npm ci
            - name: Build
              run: npm run build
